apiVersion: v1
name: assemblyline
version: 7.1.0
appVersion: "4.7.1.stable0"
description: Assemblyline is a malware detection and analysis tool developed by the Cyber Centre and released to the cyber security community.
keywords: [assemblyline, malware, gc, canada, cse-cst, cse, cst, cyber, cccs]
home: https://cyber.gc.ca/en/assemblyline
sources:
  - https://github.com/CybercentreCanada/
icon: https://bitbucket-assetroot.s3.amazonaws.com/c/photos/2018/Nov/06/2199173190-1-alv4-logo_avatar.png
