{{ if .Values.internalFilestore }}
{{ if not (lookup "v1" "Secret" .Release.Namespace "internal-filestore-keys") }}
apiVersion: v1
kind: Secret
metadata:
  name: internal-filestore-keys
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  accesskey: {{ randAlphaNum 16 }}
  secretkey: {{ randAlphaNum 16 }}
{{ end }}
{{ end }}
---
{{ if or .Values.internalDatastore .Values.seperateInternalELKStack}}
apiVersion: v1
kind: Secret
metadata:
  name: elastic-helper-secret
data:
  {{- if .Release.IsInstall }}
  password: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  password:  {{ index (lookup "v1" "Secret" .Release.Namespace "elastic-helper-secret" | default (dict "data" (dict "password" (randAlphaNum 20 | b64enc)))).data "password" }}
  {{ end }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
data:
  {{- if .Release.IsInstall }}
  password: {{ randAlphaNum 80 | b64enc }}
  {{ else }}
  password:  {{ index (lookup "v1" "Secret" .Release.Namespace "flask-secret" | default (dict "data" (dict "password" (randAlphaNum 80 | b64enc)))).data "password" }}
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: service-secret
data:
  {{- if .Release.IsInstall }}
  password: {{ randAlphaNum 80 | b64enc }}
  {{ else }}
  password:  {{ index (lookup "v1" "Secret" .Release.Namespace "service-secret" | default (dict "data" (dict "password" (randAlphaNum 80 | b64enc)))).data "password" }}
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: retrohunt-secret
data:
  {{- if .Release.IsInstall }}
  password: {{ randAlphaNum 80 | b64enc }}
  {{ else }}
  password:  {{ index (lookup "v1" "Secret" .Release.Namespace "retrohunt-secret" | default (dict "data" (dict "password" (randAlphaNum 80 | b64enc)))).data "password" }}
  {{ end }}
